#!/bin/bash

sudo add-apt-repository ppa:fossfreedom/byzanz

wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y
sudo add-apt-repository ppa:webupd8team/java

sudo apt-get update

sudo apt-get install byzanz node tiptop gimp htop traceroute apache2 virtualbox clamav php5-cli shellcheck maven npm openvpn gimp htop mysql-server openvpn oracle-java8-installer fail2ban ttf-liberation nmap iftop dos2unix vagrant git eclipse meld sublime-text-installer google-chrome-stable ntp ntpdate lm-sensors psensor unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller parallel expect ruby ruby-dev compizconfig-settings-manager libxml2-utils iftop htop openssh-server -y


sudo npm install -g diff-so-fancy
sudo gem install travis -v 1.8.2 --no-rdoc --no-ri

sudo sensors-detect --auto

sudo apt-get -y upgrade

sudo apt autoremove -y
