#!/bin/bash

GIT_NAME=$1
GIT_EMAIL=$2

function usage() {
  echo "usage: $(basename $0) <git_name> <git_email>"
  exit 1
}

if [[ -z "$GIT_NAME" ]] || [[ -z "$GIT_EMAIL" ]]; then
  usage
fi

git config --global user.email "$GIT_EMAIL"
git config --global user.name "$GIT_NAME"
git config --global core.editor vi
git config --global merge.tool meld
git config --global core.autocrlf input
git config branch.autosetuprebase always --global
git config --global push.default simple
git config --global core.pager "diff-so-fancy | less --tabs=2 -RFX"

# fancy diff color
git config --global color.diff-highlight.oldNormal "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"

