- name: upgrade apt
  become: true
  apt:
    cache_valid_time: 86400 ## one day
    upgrade: yes

- name: install apt packages
  become: true
  register: apt_status
  package:
    state: present
    name:
      - clamav
      - clamav-daemon
      - curl
      - dos2unix
      - expect
      - fail2ban
      - file-roller
      - gimp
      - htop
      - iftop
      - libxml2-utils
      - lm-sensors
      - meld
      - nmap
      - npm
      - ntp
      - ntpdate
      - p7zip-full
      - p7zip-rar
      - parallel
      - postgresql-client
      - preload
      - psensor
      - rar
      - ruby
      - ruby-dev
      - sharutils
      - shellcheck
      - traceroute
      - tree
      - unace
      - unrar
      - unzip
      - vim
      - wget
      - zip

- name: run sensors detect
  shell: sensors-detect --auto
  become: true
  when: apt_status.changed

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

