- name: upgrade apt
  become: true
  apt:
    cache_valid_time: 86400 ## one day
    upgrade: yes

- name: install snap packages
  become: true
  snap:
    name:
      - brave
      - intellij-idea-ultimate
      - steam

- name: stop app armor
  become: true
  service:
    state: stopped
    name: apparmor

- name: remove app armor
  become: true
  command: update-rc.d -f apparmor remove

- name: remove apparmor
  become: true
  package:
    state: absent
    name:
      - apparmor
      - apparmor-utils

- name: make sure snapd is still present
  become: true
  package:
    state: present
    name: snapd

- name: remove firefox snap
  become: true
  snap:
    state: absent
    name: firefox

- name: install apt packages
  become: true
  register: apt_status
  package:
    state: present
    name:
      - bash-completion
      - ca-certificates
      - clamav
      - clamav-daemon
      - curl
      - dos2unix
      - expect
      - fail2ban
      - file-roller
      - gimp
      - gnupg
      - htop
      - iftop
      - libxml2-utils
      - lm-sensors
      - lsb-release
      - meld
      - nmap
      - npm
      - ntp
      - ntpdate
      - p7zip-full
      - p7zip-rar
      - parallel
      - postgresql-client
      - preload
      - psensor
      - python3
      - python-is-python3
      - rar
      - rsyslog
      - ruby
      - ruby-dev
      - sharutils
      - shellcheck
      - traceroute
      - tree
      - unace
      - unrar
      - unzip
      - vim
      - whiptail
      - wget
      - zip

- name: run sensors detect
  shell: sensors-detect --auto
  become: true
  when: apt_status.changed

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: ensure firewall is running
  become: true
  service:
    state: started
    name: ufw
    enabled: true

- name: Upgrade all apt packages
  become: true
  apt:
    update_cache: true
    upgrade: dist
