- name: APT
  block:
    - name: upgrade apt
      become: true
      when: not ansible_check_mode
      apt:
        cache_valid_time: 3600 ## one hour
        upgrade: yes

    - name: Remove dependencies that are no longer required
      when: not ansible_check_mode
      become: true
      apt:
        autoremove: yes

    - name: install apt packages
      become: true
      when: not ansible_check_mode
      register: apt_status
      package:
        state: present
        name:
          - bash-completion
          - ca-certificates
          - clamav
          - clamav-daemon
          - curl
          - dos2unix
          - expect
          - fail2ban
          - file-roller
          - gimp
          - gnupg
          - htop
          - iftop
          - libxml2-utils
          - lm-sensors
          - lsb-release
          - meld
          - nmap
          - npm
          - ntp
          - ntpdate
          - p7zip-full
          - p7zip-rar
          - parallel
          - postgresql-client
          - preload
          - psensor
          - python3
          - python-is-python3
          - rar
          - rsyslog
          - ruby
          - ruby-dev
          - sharutils
          - shellcheck
          - snapd
          - traceroute
          - tree
          - unace
          - unrar
          - unzip
          - vim
          - whiptail
          - wget
          - zip

- name: run sensors detect
  when: not ansible_check_mode and apt_status.changed
  become: true
  shell: sensors-detect --auto

- name: Snap Packages
  block:
    - name: install snap packages
      when: not ansible_check_mode
      become: true
      notify: snapd_running
      snap:
        name:
          - brave
          - steam

    - name: install classic snap packages
      when: not ansible_check_mode
      become: true
      notify: snapd_running
      snap:
        name:
          - intellij-idea-ultimate
        classic: true

    - name: make sure snapd is still present
      when: not ansible_check_mode
      become: true
      notify: snapd_running
      package:
        state: present
        name: snapd

- name: Security Settings
  block:
    - name: ensure firewall is running
      when: not ansible_check_mode
      become: true
      service:
        state: started
        name: ufw
        enabled: true
    - name: Disable kernel address visibility, disallowed to all users including root (kptr_restrict = 2)
      ansible.builtin.replace:
        path: /etc/sysctl.d/10-kernel-hardening.conf
        regexp: '(kernel\.kptr_restrict = ).*'
        replace: '\g<1>2'
      become: true

    - name: Disallow SSH password login
      ansible.builtin.replace:
        path: /etc/ssh/ssh_config
        regexp: '^#(.*PasswordAuthentication) .*'
        replace: '\1 no'
      become: true
