
- name: create docker group
  become: true
  group: 
    name: docker
    state: present

- name: sudoless docker commands
  become: true 
  user:
    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
    groups: docker
    append: yes

- name: run docker on startup
  service:
    name: docker
    state: started
    enabled: true 
